# Generated by Django 2.0.3 on 2018-03-24 20:56

from django.db import migrations, models
import django.db.models.deletion



def create_continent(apps, schema_editor):
    Continent = apps.get_model("continentes","Continent")

    Continent.objects.create(name="asia", color="#EE65EE", translate="asia")
    Continent.objects.create(name="america", color="#000", translate="america")
    Continent.objects.create(name="antartida", color="#FFFF00", translate="antartida")
    Continent.objects.create(name="europa", color="#F1d142", translate="europa")
    Continent.objects.create(name="africa", color="#F04261", translate="africa")
    Continent.objects.create(name="oceania", color="#EE65DD", translate="oceania")


class Migration(migrations.Migration):

    dependencies = [
        ('continentes', '0001_initial'),
        ('countries', '0002_auto_20180324_1926'),
    ]

    operations = [
        migrations.RunPython(create_continent),
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='continentes.Continent'),
            preserve_default=False,
        ),
    ]
